// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZS3K2RP24ANLYea3r_xreSSPN3g6roU',
    appId: '1:1072608551301:web:e4ff8fc95cfd0328ff24ec',
    messagingSenderId: '1072608551301',
    projectId: 'sig-in-a9c72',
    authDomain: 'sig-in-a9c72.firebaseapp.com',
    storageBucket: 'sig-in-a9c72.appspot.com',
    measurementId: 'G-QP0ZHRPCGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATg6QYTgho8Bs3wPpvnFXUJX_TnxYu_EU',
    appId: '1:1072608551301:android:7d2c7c24980abdccff24ec',
    messagingSenderId: '1072608551301',
    projectId: 'sig-in-a9c72',
    storageBucket: 'sig-in-a9c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUJauzuLGxGveGWR_Qv5PX-TCeCeeN8c',
    appId: '1:1072608551301:ios:0be49ba9c44d233cff24ec',
    messagingSenderId: '1072608551301',
    projectId: 'sig-in-a9c72',
    storageBucket: 'sig-in-a9c72.appspot.com',
    androidClientId: '1072608551301-2ec3mkirmmjf1vm52lpmhih5kl478a6j.apps.googleusercontent.com',
    iosClientId: '1072608551301-2j5iivn0umhbb9k6cntqnmn0jbts7hd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUJauzuLGxGveGWR_Qv5PX-TCeCeeN8c',
    appId: '1:1072608551301:ios:3a236d3c34866661ff24ec',
    messagingSenderId: '1072608551301',
    projectId: 'sig-in-a9c72',
    storageBucket: 'sig-in-a9c72.appspot.com',
    androidClientId: '1072608551301-2ec3mkirmmjf1vm52lpmhih5kl478a6j.apps.googleusercontent.com',
    iosClientId: '1072608551301-puotqt0v2ea4kpjm63ov8garfh4a7fkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasAndroid.RunnerTests',
  );
}
